# Generated by Django 5.2.14 on 2026-05-17 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['user', '-id'], name='asset_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', '-created_at'], name='gen_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', 'status'], name='gen_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status'], name='gen_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('generation', 'r2_key'), name='asset_gen_r2key_uniq'),
        ),
    ]
